on: [push, workflow_dispatch]
jobs:
  build:
    name: Greeting
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      shell: cmd
      run: |
        netsh advfirewall firewall add rule name="Open Port 10731" dir=in action=allow protocol=TCP localport=10731
        go run http-servers.go &
        curl http://127.0.0.1:10731/hello
