on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: brew re-install
      run: |
        brew update
        brew reinstall gcc@8
