on: [push, workflow_dispatch]
jobs:
  build:
    name: Greeting
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      shell: cmd
      run: |
        go run http-servers.go &
        curl http://127.0.0.1:8090/hello
