on: [ push, pull_request ]

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: maxim-lobanov/setup-java@adoptium
        with:
          java-version: '17-ea'
          distribution: 'adopt'
      - run: java -version
      - uses: maxim-lobanov/setup-java@adoptium
        with:
          java-version: '17-ea'
          distribution: 'adopt'
      - run: java -version  
