on: [ push, pull_request ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -la /opt
    - run: |
        ls -la /usr/share
    - run: |
        ls -la /home
        
