on: [ push, pull_request ]

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '*'
