on: [ push, pull_request ]

jobs:

  test1:
    runs-on: windows-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.9.0
      - name: Generate pnpm file
        run: | 
          New-Item -ItemType Directory -Path "C:\Temp2"
          cd "C:\Temp2"
          Get-ChildItem 
          pnpm store path
