name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-14.04'
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
