on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
       ls -la /home/runner/agents
       echo "-----"
       ls -la /home/runner/agents/2.195.0/.setup_info
       echo "------"
       cat /home/runner/agents/2.195.0/.setup_info
