name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
