on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        chown root:docker -R /usr/share/rust
    - run: |
        ls -la /usr/share/rust/.cargo/env
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: /usr/share/rust/.cargo/env
        key: a1
    - run: |
        ls -la /usr/share/rust/.cargo/env
        
        
