name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'macos-latest'
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.10
    - run: ls -la  /Users/runner/hostedtoolcache/jdk/11.0.10/x64
      
