name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  get-msedgedriver-version:
    runs-on: 'macos-10.15'
    steps:
      - name: Download driver
        run: |
          wget https://msedgedriver.azureedge.net/87.0.630.0/edgedriver_mac64.zip
          unzip -a edgedriver_mac64.zip
          ./msedgedriver --version
