name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'windows-latest'
    steps:
    - uses: microsoft/setup-msbuild@v1
    #- uses: seanmiddleditch/gha-setup-vsdevenv@master
    - run: nmake /?
