name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Archive
        run: |
          tar -czvf $HOME/Downloads/nvm.tar.gz -C $HOME/.nvm .
      - name: Unpack
        run: |
          mkdir $HOME/Downloads/nvm2
          tar -xvzf $HOME/Downloads/nvm.tar.gz -C $HOME/Downloads/nvm2
          mkdir $HOME/temp
      - name: Collect hash
        run: |
          Get-ChildItem -Path $env:HOME/.nvm -Recurse | ForEach-Object {
            $hash = Get-FileHash $_.FullName | Select-Object -ExpandProperty Hash
            return "$($_.FullName) -> $hash"
          } | Out-File -Path $env:HOME/temp/nvm1.txt
          Get-ChildItem -Path $env:HOME/Downloads/nvm2 -Recurse | ForEach-Object {
            $hash = Get-FileHash $_.FullName | Select-Object -ExpandProperty Hash
            return "$($_.FullName) -> $hash"
          } | Out-File -Path $env:HOME/temp/nvm2.txt
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: Test
          path: $HOME/temp
      
