on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - run: |
          $osVersion = [Environment]::OSVersion
          $osVersionMajorMinor = $osVersion.Version.ToString(2)
          $osVersion
          $osVersionMajorMinor
        shell: pwsh
