name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Setup Java JDK
      uses: maxim-lobanov/setup-java@v-malob/add-5-digits-support
      with:
        java-version: 8.0
        distribution: adoptium
    - run: |
        mv /opt/hostedtoolcache/Java_Adoptium_jdk/8.0.282 /opt/hostedtoolcache/Java_Adoptium_jdk/8.0.282+8
        ls -la /opt/hostedtoolcache/Java_Adoptium_jdk
        echo "----"
        ls -la /opt/hostedtoolcache/Java_Adoptium_jdk/8.0.282+8
        echo "----"
        ls -la /opt/hostedtoolcache/Java_Adoptium_jdk/8.0.282+8/x64
    - name: Setup Java JDK
      uses: maxim-lobanov/setup-java@v-malob/add-5-digits-support
      with:
        java-version: 8
        distribution: adoptium
