on: [ push, pull_request ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        Get-ChildItem "C:\Program Files\Docker"
    - run: |
        Remove-Item -Path "C:\Program Files\Docker\docker-credential-wincred.exe" -Force
    - run: |
        Get-Command "docker-credential-wincred.exe"
        
