on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    name: Go
    steps:
      - uses: actions/checkout@v2
      - run: echo "CONDA=" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Conda info
        shell: bash -l {0}
        run: conda info
