on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - run: |
        mv $HOME/.docker/config.json $HOME/.docker/config.json.tmp
        ls -la $HOME/.docker
    - run: |
        docker info
        docker login | true
    - run: |
        docker logout
    - run: |
        mv $HOME/.docker/config.json.tmp $HOME/.docker/config.json
        ls -la $HOME/.docker
    - run: |
        docker info
    - run: |
        docker login
    
    
