name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'macos-latest'
    steps:
    - name: Setup Java JDK
      uses: maxim-lobanov/setup-java@add-main-warning
      with:
        java-version: 15
    - run: ls -la  /Users/runner/hostedtoolcache/jdk/8.*/x64
    - run: |
        cd /Users/runner/hostedtoolcache/jdk/8.*/x64
        find . -type l -ls
      
