on: [ push, pull_request ]

jobs:
  versions-macOS-110:
    name: macOS 11
    runs-on: macos-11
    strategy:
      matrix:
        xcode-version: ['12.5', '13', '13.0', '13.0.0', '13.0-beta', '13.0.0-beta', '12.5-beta', latest, latest-stable]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: einar-notland/setup-xcode@stableSemver
      name: Setup Xcode
      id: setup-xcode
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Print output variables
      run: |
        echo "Version: ${{ steps.setup-xcode.outputs.version }}"
        echo "Path: ${{ steps.setup-xcode.outputs.path }}"
