name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@main
      with:
        java-version: 15
