on: [ push, pull_request ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        $env:PATH
        
        Get-Command "docker"
        
