on: [ push, pull_request ]

jobs:

  write-hello:
    runs-on: macos-latest
    steps:
      - run: /Applications/Visual Studio.app/Contents/MacOS/Visual Studio Update.app
      - run: ps $$
      - run: ps
     
