on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - run: |
        Write-Host "[STOPWATCH] Test-Connection ($(Get-Date))";
        $stopwatch = [system.diagnostics.stopwatch]::StartNew()
        $connectionTests = @('google.com') | ForEach-Object { New-Object System.Net.Sockets.TCPClient -ArgumentList $_, 80 }
        if ($connectionTests.Connected -notcontains $true) { throw 'Failed to connect to internet' }
        Write-Host 'Connected to internet'
        $stopwatch.Stop();
        Write-Host "[STOPWATCH] Test-Connection: $($stopwatch.Elapsed.TotalSeconds) ms ($(Get-Date))"
      shell: powershell
