on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - run: |
        Get-ChildItem $env:USERPROFILE
        
        Get-ChildItem "$env:USERPROFILE\.docker"
      shell: powershell
