name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.0.0-ea'
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.0.0'
