name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'windows-latest'
    steps:
      - uses: maxim-lobanov/actions/setup@support-choco-ghc-new-path
        with:
          ghc-version: '9.0.1'
      - run: ghc --version
