on: [ push, pull_request ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -la /opt/az
        echo "-----"
        ls -la /opt/google
    - run: |
        ls -la /usr/share
        echo "--------"
        ls -la /usr/share/cmake
    - run: |
        ls -la /home/linuxbrew
        ls -la /runneradmin
        
