on: [ push, pull_request ]

jobs:

  write-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: hello
          key: hello

      - run: echo "Hello, world!" > hello


  read-hello:
    needs: write-hello
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: hello
          key: hello
