name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  build:
   runs-on: macos-latest
   steps:
     - run: | 
         printenv | sort
     - run: |
          #sudo ${ANDROID_HOME}/tools/bin/sdkmanager --list
          $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;21.3.6528147"
