on: [ push, pull_request ]

jobs:

  test1:
    runs-on: windows-latest
    steps:
      - uses: joschi/setup-java@adoptium
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: java -version
