on: [ push, pull_request ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -la /opt/az/include
        # echo "0" > /opt/az/mystuff.txt
        echo "-----"
        ls -la /opt/google/chrome
        # rm -rf /opt/google/chrome
    - run: |
        # rm -f "/usr/share/az_5.9.0.zip
        ls -la /usr/share/apache-maven-3.8.3
        echo "--------"
        echo "1" > /usr/share/cmake/bash-completion
    - run: |
        ls -la /home/linuxbrew/.linuxbrew
        
