on: [ push, pull_request ]

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chmod 777 /usr/local/lib/node_modules -R
      - run: npm install -g pnpm
      - run: pnpm --version
