on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        Get-ChildItem C:\actions\settings\factory | ForEach-Object { Write-Host "-------------------"; Write-Host $_.Name; Write-Host "-------------------"; Write-Host (Get-Content $.FullName) }
    - run: |
         Get-ChildItem C:\actions\settings\warmup | ForEach-Object { Write-Host "-------------------"; Write-Host $_.Name; Write-Host "-------------------"; Write-Host (Get-Content $.FullName) }
    
    
