on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - shell: pwsh
      run: |
        $url = "https://github.com/actions/go-versions/releases/download/1.18.0-1989285564/go-1.18.0-win32-x64.zip"
        Invoke-WebRequest -Uri $url -OutFile ./go.zip
    - shell: pwsh
      run: |
        unzip -qq go.zip
      
    
    
