on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: windows-latest
    steps:
    - run: |
        function Ping-Connection($Url) { $tcpClient = New-Object System.Net.Sockets.TCPClient; try { $tcpClient.Connect($Url, 80) } catch {} finally { $result = $tcpClient.Connected; $tcpClient.Dispose(); if ($result) { Write-Host 'Connected to', $Url } else { Write-Host 'Failed to connect to', $Url }; $result } }
        if (-not ((Ping-Connection "gagawoogle.com") -or (Ping-Connection "githaub.com"))) { throw "Failed to connect internet" }
      shell: powershell
