name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Archive
        run: |
          tar -czvf $HOME/Downloads/nvm.tar.gz -C $HOME/.nvm .
      - name: Unpack
        run: |
          tar -xvzf $HOME/Downloads/nvm.tar.gz -C $HOME/Downloads/nvm2
      - name: Collect hash
        run: |
          mkdir $HOME/temp
          find $HOME/.nvm -type f -exec md5sum {} + | sort -k 2 > $HOME/temp/nvm1.txt
          find $HOME/Downloads/nvm2 -type f -exec md5sum {} + | sort -k 2 > $HOME/temp/nvm2.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Test
          path: $HOME/temp
      
