on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -la /home/runner
        echo "-----"
        ls -la /home/runner/work
