name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: 'macos-latest'
    steps:
     - run: |
          ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147" >> $GITHUB_ENV
     - run: |
         echo $ANDROID_NDK_HOME
         ls -la $ANDROID_NDK_HOME
          
