on: [ push, pull_request ]

jobs:

  write-hello:
    runs-on: macos-11
    steps:
      - run: |
         echo "::warning::Missing semicolon"
         
  write-hello2:
    runs-on: macos-11
    steps:
      - run: |
         echo "::warning::Another warning"
     
