name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17-ea
        java-package: jdk
        architecture: x64
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
