on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat /imagegeneration/imagedata.json
  rider-win:
    name: Rider-Win
    runs-on: windows-latest
    steps:
    - run: |
        Get-Content C:\\imagedata.json
