on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - run: |

        Get-ChildItem "$env:USERPROFILE\.docker"
        Get-Content "C:\Users\runneradmin\.docker\config.json"
      shell: pwsh
