on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo chown root:root -R /usr/share/rust
        sudo rm -rf /etc/skel/.rustup
        sudo rm -rf /etc/skel/.cargo
        ls -la /usr/share/rust
        ls -la /etc/skel
    - run: |
        sudo cp -rp /usr/share/rust/.cargo /etc/skel
        sudo cp -rp /usr/share/rust/.rustup /etc/skel
        ls -la /etc/skel
        ls -la /etc/skel/.cargo
    - run: |
        sudo useradd testuser
        sudo passwd -d testuser

        su testuser -c "echo hello"
        ls -la /home
        ls -la /home/testuser
    - run: |
        ls -la /usr/share/rust/.cargo/bin
    #- name: Cache
    #  uses: actions/cache@v2.1.6
   #   with:
    #    path: /usr/share/rust/.cargo/bin
   #     key: a4
    #- run: |
    #    ls -la /usr/share/rust/.cargo/bin
        
        
