on: [ push, workflow_dispatch ]

jobs:
  rider:
    name: Rider
    runs-on: ubuntu-latest
    steps:
    - run: |
        ls -la $HOME/.docker
    - run: |
        docker info
    - run: |
        docker login
    
    
