name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'windows-latest'
    steps:
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
      - run: ghc --version
