name: 'test'
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: 'ubuntu-latest'
    container: hseeberger/scala-sbt:graalvm-ce-20.0.0-java8_1.3.13_2.13.3
    steps:
    - run: echo "hello world"
    - run: echo "hello world"
